#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	// Plugin IDs
	PID_COLOR_MANAGEMENT_EXAMPLES = 1059947,
	PID_OCIO_EXAMPLES = 1060231,

	// Command IDs
	CID_CLEAR_CONSOLE = 13957,
	CID_OPEN_CONSOLE = 12305,

	// String IDs
	IDS_NME_COLOR_MANAGEMENT_EXAMPLES = 10000,
	IDS_HLP_COLOR_MANAGEMENT_EXAMPLES,
	IDS_NME_OCIO_EXAMPLES,
	IDS_HLP_OCIO_EXAMPLES,

	// End of symbol definition
	_DUMMY_ELEMENT_
};

#endif //C4D_SYMBOLS_H__
