CONTAINER VPocioawarerenderer
{
  NAME VPocioawarerenderer;
  INCLUDE VPbase;

  GROUP ID_VIDEOPOSTPROPERTIES
  {
    COLOR ID_RENDER_COLOR	{ OPEN; }
    BOOL ID_PRETRANSFORM_OCIO_OUTPUT { ANIM OFF; }
    BOOL ID_OVERWRITE_OCIO_DISPLAY_SPACE { ANIM OFF; }
    BOOL ID_OVERWRITE_OCIO_VIEW_TRANSFORM { ANIM OFF; }
  }
}
