#ifndef VPOCIOAWARERENDERER_H__
#define VPOCIOAWARERENDERER_H__

enum
{
  ID_RENDER_COLOR = 1000,
  ID_PRETRANSFORM_OCIO_OUTPUT,
  ID_OVERWRITE_OCIO_DISPLAY_SPACE,
  ID_OVERWRITE_OCIO_VIEW_TRANSFORM
};

#endif // VPOCIOAWARERENDERER_H__
