// C4D-DialogResource

DIALOG DLG_SMPL_MATRIX
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_SMPL_MATRIX_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_FILTERTYP; }
			COMBOBOX GADGET_SMPL_MATRIX_TYPE_POPUP
			{
			 	CHILDS
			 	{
					0, STR_POPUP_ID0;
					1, STR_POPUP_ID1;
				}
			} 

			STATICTEXT { ALIGN_RIGHT; NAME STR_ANGLE; }
			EDITSLIDER GADGET_SMPL_MATRIX_SLIDER_ANGLE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_SMPL_MATRIX_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_SMPL_MATRIX_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_SMPL_MATRIX_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}