// C4D-DialogResource
DIALOG IDD_SHADER_BROWSER
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
    LINK IDC_LAYER_BROWSER_LINK
    {
      ALIGN_TOP; SCALE_H; 
    }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC2; SCALE_V; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 2;
    ALLOW_WEIGHTS; 
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
    TREEVIEW IDC_LAYER_BROWSER_TREE
    {
      SCALE_V; SCALE_H; 
      BORDER; 
      NO_MULTISELECT; 
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
    MULTILINEEDIT IDC_LAYER_BROWSER_PROPS
    { SCALE_V; SCALE_H; SIZE 70, 0; }
  }
}