#ifndef ODESCRIPTION_H__
#define ODESCRIPTION_H__

enum
{
	ID_GROUP_CONTROL = 1000,
	ID_SELECT_DESCRIPTION,
	ID_SET_PARAMETER,
	ID_GET_PARAMETER,
	ID_GROUP_DYNAMIC,
	ID_DYNAMIC_ELEMENT = 2000,

	ID_GROUP_RESULT = 5000,
	ID_RESULT_TEXT

};

#endif // ODESCRIPTION_H__
