CONTAINER Oedrop
{
	NAME		Oedrop;

	INCLUDE Obase;

	GROUP		DROPEFFECTOR_GROUPEFFECTOR
	{
		DEFAULT 1;

		REAL	DROPEFFECTOR_STRENGTH
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		SEPARATOR
		{
			LINE;
		}
		LINK	DROPEFFECTOR_TARGET 
		{
			ACCEPT
			{
				Obase;
			}
			REFUSE
			{
				Osky;
				Oforeground;
			}
		}
		LONG	DROPEFFECTOR_MODE
		{
			CYCLE
			{
				DROPEFFECTOR_MODE_AXIS;
				DROPEFFECTOR_MODE_SELFAXIS;
				DROPEFFECTOR_MODE_PNORMAL;
				DROPEFFECTOR_MODE_NNORMAL;
				DROPEFFECTOR_MODE_PX;
				DROPEFFECTOR_MODE_PY;
				DROPEFFECTOR_MODE_PZ;
				DROPEFFECTOR_MODE_NX;
				DROPEFFECTOR_MODE_NY;
				DROPEFFECTOR_MODE_NZ;
			}
		}
		REAL DROPEFFECTOR_DISTANCE { MIN 1.0; UNIT METER; }
	}
	INCLUDE Oedeformer_panel;
}
