#ifndef OGREEKTEMPLE_H__
#define OGREEKTEMPLE_H__

enum
{
  SDK_EXAMPLE_GREEKTEMPLE_WIDTH					= 1000,
  SDK_EXAMPLE_GREEKTEMPLE_HEIGHT				= 1001,
  SDK_EXAMPLE_GREEKTEMPLE_LENGTH				= 1002,
  SDK_EXAMPLE_GREEKTEMPLE_X_SEGMENTS		= 1003,
  SDK_EXAMPLE_GREEKTEMPLE_Y_SEGMENTS		= 1004,
  SDK_EXAMPLE_GREEKTEMPLE_Z_SEGMENTS		= 1005,
  SDK_EXAMPLE_GREEKTEMPLE_STAIRS				= 1006,
  SDK_EXAMPLE_GREEKTEMPLE_COLS_SPACEX		= 1007,
  SDK_EXAMPLE_GREEKTEMPLE_COLS_SPACEZ		= 1008,


	SDK_EXAMPLE_GREEKTEMPLE								= 2000
};

#endif // OGREEKTEMPLE_H__
