CONTAINER Ohairsdkcollider
{
	NAME Ohairsdkcollider;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		REAL HAIRSDK_COLLIDER_BOUNCE { UNIT PERCENT; }
		REAL HAIRSDK_COLLIDER_FRICTION { UNIT PERCENT; }

		REAL HAIRSDK_COLLIDER_WIDTH { UNIT METER; MIN 0.0; }
		REAL HAIRSDK_COLLIDER_HEIGHT { UNIT METER; MIN 0.0; }
	}
}
