CONTAINER Ohairsdkgen
{
	NAME Ohairsdkgen;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		BOOL HAIR_GEN_GENERATE { }

		LINK HAIR_GEN_LINK { ACCEPT { 5100; Tpolygonselection; 5682; } }

		GROUP
		{
			COLUMNS 2;
			
			LONG HAIR_GEN_COUNT { MIN 1; }
			LONG HAIR_GEN_SEGMENTS { MIN 1; MAX 4096; }
			
			REAL HAIR_GEN_LENGTH { UNIT METER; MIN 0.0; }
			REAL HAIR_GEN_LENGTH_VAR { UNIT METER; MIN 0.0; }

			REAL HAIR_GEN_NOISE { UNIT PERCENT; MIN 0.0; }
		}
	}
}
