CONTAINER Ohairsdkdeformer
{
	NAME Ohairsdkdeformer;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		REAL HAIR_DEFORMER_STRENGTH { UNIT PERCENT; }

		LINK HAIR_DEFORMER_COMB_X { ACCEPT { 5682; } }
		LINK HAIR_DEFORMER_COMB_Y { ACCEPT { 5682; } }
		LINK HAIR_DEFORMER_COMB_Z { ACCEPT { 5682; } }
	}
}
