#ifndef OHAIRSDKCOLLIDER_H__
#define OHAIRSDKCOLLIDER_H__

enum
{
	HAIRSDK_COLLIDER_BOUNCE = 2000,
	HAIRSDK_COLLIDER_FRICTION = 2001,
	HAIRSDK_COLLIDER_WIDTH = 2002,
	HAIRSDK_COLLIDER_HEIGHT = 2003,

	//////////////////////////////////////////////////////////////////////////

	_HAIRSDK_COLLIDER_END_
};

#endif // OHAIRSDKCOLLIDER_H__
