#ifndef OLOFTEDMESH_H__
#define OLOFTEDMESH_H__

enum
{
	SDK_EXAMPLE_LOFTEDMESH_S_STEPS      	= 1000,
	SDK_EXAMPLE_LOFTEDMESH_T_STEPS      	= 1001,
	SDK_EXAMPLE_LOFTEDMESH_INTERPOLATION    = 1002,
		SDK_EXAMPLE_SPLINETYPE_LINEAR	= 0,
		SDK_EXAMPLE_SPLINETYPE_CUBIC	= 1,
		SDK_EXAMPLE_SPLINETYPE_AKIMA	= 2,
		SDK_EXAMPLE_SPLINETYPE_BSPLINE	= 3,
		SDK_EXAMPLE_SPLINETYPE_BEZIER	= 4
};

#endif // OOBJECTDATA_LOFTEDMESH_H__
