CONTAINER oplanebypolygons
{
	NAME oplanebypolygons;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SDK_EXAMPLE_PLANEBYPOLYGONS_WIDTH      { UNIT METER; MIN 0.0; }
		REAL SDK_EXAMPLE_PLANEBYPOLYGONS_HEIGHT     { UNIT METER; MIN 0.0; }
		LONG SDK_EXAMPLE_PLANEBYPOLYGONS_W_SUBD     { MIN 1; MAX 256; }
		LONG SDK_EXAMPLE_PLANEBYPOLYGONS_H_SUBD     { MIN 1; MAX 256; }
		BOOL SDK_EXAMPLE_PLANEBYPOLYGONS_USE_TRIS   { }
	}
}