#ifndef OPORCUPINEMODIFIER_H__
#define OPORCUPINEMODIFIER_H__

enum
{
	SDK_EXAMPLE_PORCUPINEMODIFIER_PERCENTAGE    = 1000,
	SDK_EXAMPLE_PORCUPINEMODIFIER_LEVEL         = 1001
};

#endif // OPORCUPINEMODIFIER_H__
