#ifndef OSHUFFLINGPARTICLES_H__
#define OSHUFFLINGPARTICLES_H__

enum
{
	SDK_EXAMPLE_SHUFFLINGPARTICLES_SEED = 1000,
	SDK_EXAMPLE_SHUFFLINGPARTICLES_STRENGTH = 1001,
	SDK_EXAMPLE_SHUFFLINGPARTICLES_SIZE_X = 1002,
	SDK_EXAMPLE_SHUFFLINGPARTICLES_SIZE_Y = 1003,
	SDK_EXAMPLE_SHUFFLINGPARTICLES_SIZE_Z = 1004
};

#endif // OSHUFFLINGPARTICLES_H__
