#ifndef OVERTEXHANDLE_H__
#define OVERTEXHANDLE_H__

enum
{
	SDK_EXAMPLE_VERTEXHANDLE_POINT_A_DIST   = 1000,
	SDK_EXAMPLE_VERTEXHANDLE_POINT_B_DIST   = 1001,
	SDK_EXAMPLE_VERTEXHANDLE_POINT_C_DIST   = 1002
};

#endif // OVERTEXHANDLE_H__
