#ifndef TOOLSCULPTGRABBRUSH_H__
#define TOOLSCULPTGRABBRUSH_H__

enum
{
	ToolSculptGrabBrush_Start = 20000,

	MDATA_TOOLSCULPTGRABBRUSH_DIRMODE,
	MDATA_TOOLSCULPTGRABBRUSH_DIRMODE_MOUSEDIR,
	MDATA_TOOLSCULPTGRABBRUSH_DIRMODE_NORMAL,
};

#endif // TOOLSCULPTGRABBRUSH_H__
