#ifndef TOOLEDGECUTSDK_H__
#define TOOLEDGECUTSDK_H__

enum
{
	MDATA_EDGECUTSDK_SUBDIV				= 2133,
	MDATA_EDGECUTSDK_OFFSET				= 2166,
	MDATA_EDGECUTSDK_SCALE				= 2165,
	MDATA_EDGECUTSDK_CREATENGONS 	= 2167
};

#endif // TOOLEDGECUTSDK_H__
