CONTAINER ToolPaintBrushBase
{
  NAME ToolPaintBrushBase;
  INCLUDE toolsculptbrushbase;
  HIDE MDATA_SCULPTBRUSH_STAMP_MIDVALUE;
  HIDE MDATA_SCULPTBRUSH_STAMP_SHOWDEPTH;
  HIDE MDATA_SCULPTBRUSH_STAMP_INTERPOLATE;
  HIDE MDATA_SCULPTBRUSH_STENCIL_MIDVALUE;  
}
