#ifndef OLATTICEPLANEMODIFIER_H__
#define OLATTICEPLANEMODIFIER_H__

enum
{
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_SSIZE						= 1000,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_TSIZE						= 1001,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_SSEGS						= 1002,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_TSEGS						= 1003,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE						= 1004,
		SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE_UNLIMITED 			= 0,
		SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE_WITHINBOX 			= 1,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_RESETCAGE					= 1005,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_ENABLENORMALCHK			= 1006,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_NORMALTHR					= 1007,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE_GROUP					= 1008,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_CAGE_GROUP					= 1009,
	SDK_EXAMPLE_LATTICEPLANEMODIFIER_NORMAL_GROUP				= 1010
};

#endif // OLATTICEPLANEMODIFIER_H__
