CONTAINER olatticeplanemodifier
{
	NAME olatticeplanemodifier;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		GROUP SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE_GROUP
		{
			LONG SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE				
			{
				CYCLE
				{
					SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE_UNLIMITED;
					SDK_EXAMPLE_LATTICEPLANEMODIFIER_MODE_WITHINBOX;
				}
			}
		}
		GROUP SDK_EXAMPLE_LATTICEPLANEMODIFIER_CAGE_GROUP
		{
			REAL SDK_EXAMPLE_LATTICEPLANEMODIFIER_SSIZE    		{ MIN 0; UNIT METER; }
			REAL SDK_EXAMPLE_LATTICEPLANEMODIFIER_TSIZE    		{ MIN 0; UNIT METER; }

			LONG SDK_EXAMPLE_LATTICEPLANEMODIFIER_SSEGS    		{ MIN 1; MAX 128;}
			LONG SDK_EXAMPLE_LATTICEPLANEMODIFIER_TSEGS    		{ MIN 1; MAX 128;}
		}
		GROUP SDK_EXAMPLE_LATTICEPLANEMODIFIER_NORMAL_GROUP
		{
			BOOL SDK_EXAMPLE_LATTICEPLANEMODIFIER_ENABLENORMALCHK {}
			REAL SDK_EXAMPLE_LATTICEPLANEMODIFIER_NORMALTHR		{MIN 0; MAX 180; UNIT DEGREE;}
		}
		BUTTON SDK_EXAMPLE_LATTICEPLANEMODIFIER_RESETCAGE	{}
	}
}