CONTAINER oloftedmesh
{
	NAME oloftedmesh;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SDK_EXAMPLE_LOFTEDMESH_S_STEPS      { MIN 1; }
		LONG SDK_EXAMPLE_LOFTEDMESH_T_STEPS      { MIN 1; }
		LONG SDK_EXAMPLE_LOFTEDMESH_INTERPOLATION  
		{
			CYCLE
			{
				SDK_EXAMPLE_SPLINETYPE_LINEAR;
				SDK_EXAMPLE_SPLINETYPE_CUBIC;
				SDK_EXAMPLE_SPLINETYPE_AKIMA;
				SDK_EXAMPLE_SPLINETYPE_BSPLINE;
				SDK_EXAMPLE_SPLINETYPE_BEZIER;
			}
		}		
	}
}