#ifndef OPLANEBYPOLYGONS_H__
#define OPLANEBYPOLYGONS_H__

enum
{
	SDK_EXAMPLE_PLANEBYPOLYGONS_WIDTH			= 1000,
	SDK_EXAMPLE_PLANEBYPOLYGONS_HEIGHT		= 1001,
	SDK_EXAMPLE_PLANEBYPOLYGONS_W_SUBD		= 1002,
	SDK_EXAMPLE_PLANEBYPOLYGONS_H_SUBD		= 1003,
	SDK_EXAMPLE_PLANEBYPOLYGONS_USE_TRIS	= 1004
};

#endif // OPLANEBYPOLYGONS_H__
