CONTAINER oporcupinemodifier
{
	NAME oporcupinemodifier;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SDK_EXAMPLE_PORCUPINEMODIFIER_PERCENTAGE 		{ MIN 0.0; MAX 100.0; UNIT PERCENT;}
		REAL SDK_EXAMPLE_PORCUPINEMODIFIER_LEVEL       		{ MIN 0.0; MAX 100.0;}
	}
}