#ifndef OREVOLVEDMESH_H__
#define OREVOLVEDMESH_H__

enum
{
	SDK_EXAMPLE_REVOLVEDMESH_S_STEPS      	= 1000,
	SDK_EXAMPLE_REVOLVEDMESH_T_STEPS      	= 1001,
	SDK_EXAMPLE_REVOLVEDMESH_STARTANGLE		= 1002,
	SDK_EXAMPLE_REVOLVEDMESH_ENDANGLE		= 1003,
	SDK_EXAMPLE_REVOLVEDMESH_SPINNINGAXIS	= 1004
};

#endif // OREVOLVEDMESH_H__
