CONTAINER orevolvedmesh
{
	NAME orevolvedmesh;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		VECTOR SDK_EXAMPLE_REVOLVEDMESH_SPINNINGAXIS { MIN -1; MAX 1;}
		LONG SDK_EXAMPLE_REVOLVEDMESH_S_STEPS		{ MIN 16; }
		LONG SDK_EXAMPLE_REVOLVEDMESH_T_STEPS		{ MIN 16; }
		REAL SDK_EXAMPLE_REVOLVEDMESH_STARTANGLE	{ MIN -360.0; MAX 360.0; UNIT DEGREE;}
		REAL SDK_EXAMPLE_REVOLVEDMESH_ENDANGLE		{ MIN -360.0; MAX 360.0; UNIT DEGREE;}
	}
}