CONTAINER Oroundedtube
{
	NAME Oroundedtube;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL TUBEOBJECT_RAD	   		{ UNIT METER; MIN 0.0; }
		REAL TUBEOBJECT_IRADX	 		{ UNIT METER; MIN 0.0; }
		REAL TUBEOBJECT_IRADY  		{ UNIT METER; MIN 0.0; }
	  LONG TUBEOBJECT_SUB				{ MIN 1; MAX 1000; }
	  LONG TUBEOBJECT_ROUNDSUB	{ MIN 1; MAX 1000; }
		REAL TUBEOBJECT_ROUNDRAD  { UNIT METER; MIN 0.0; }
		LONG TUBEOBJECT_SEG     	{ MIN 3; MAX 1000; }
	}

	INCLUDE Oprimitiveaxis;
}
