CONTAINER oruledmesh
{
	NAME oruledmesh;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SDK_EXAMPLE_RULEDMESH_S_STEPS      { MIN 1; }
		LONG SDK_EXAMPLE_RULEDMESH_T_STEPS      { MIN 1; }
		BOOL SDK_EXAMPLE_RULEDMESH_FLIP_FIRST   {}
		BOOL SDK_EXAMPLE_RULEDMESH_FLIP_SECOND  {}
		LONG SDK_EXAMPLE_RULEDMESH_PARAM_FIRST  
		{
			CYCLE
			{
				SDK_EXAMPLE_RULEDMESH_PARAM_NATURAL;
				SDK_EXAMPLE_RULEDMESH_PARAM_UNIFORM;
			}
		}
		LONG SDK_EXAMPLE_RULEDMESH_PARAM_SECOND
		{
			CYCLE
			{
				SDK_EXAMPLE_RULEDMESH_PARAM_NATURAL;
				SDK_EXAMPLE_RULEDMESH_PARAM_UNIFORM;
			}
		}
	}
}