#ifndef ORULEDMESH_H__
#define ORULEDMESH_H__

enum
{
	SDK_EXAMPLE_RULEDMESH_S_STEPS      = 1000,
	SDK_EXAMPLE_RULEDMESH_T_STEPS      = 1001,
	SDK_EXAMPLE_RULEDMESH_FLIP_FIRST   = 1002,
	SDK_EXAMPLE_RULEDMESH_FLIP_SECOND  = 1003,
	SDK_EXAMPLE_RULEDMESH_PARAM_FIRST  = 1004,
	SDK_EXAMPLE_RULEDMESH_PARAM_SECOND = 1005,
		SDK_EXAMPLE_RULEDMESH_PARAM_NATURAL = 0,
		SDK_EXAMPLE_RULEDMESH_PARAM_UNIFORM = 1,
};

#endif // ORULEDMESH_H__
