#ifndef OSCULPTDEFORMER_H__
#define OSCULPTDEFORMER_H__

enum
{
	SCULPTDEFORMER_RADIUS			= 1000,
	SCULPTDEFORMER_PRESSURE		= 1001,
	SCULPTDEFORMER_STAMP_TEXTURE = 1002,
	SCULPTDEFORMER_STAMP_ACTIVE = 1003,
	SCULPTDEFORMER_MODIFIER = 1004,
	SCULPTDEFORMER_NUMSTAMPS = 1005,
	SCULPTDEFORMER_FALLOFF_SPLINE = 1006,
	SCULPTDEFORMER_STAMP_USEFALLOFF = 1007,
	SCULPTDEFORMER_SEED = 1008,
	SCULPTDEFORMER_STAMP_ROTATION = 1009,
};

#endif // OSCULPTDEFORMER_H__
