CONTAINER Osculptdeformer
{
	NAME Osculptdeformer;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SCULPTDEFORMER_RADIUS { MIN 0.1; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; SCALE_H; }
		REAL SCULPTDEFORMER_PRESSURE { MIN 0.01; STEP 0.1; MINSLIDER 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; UNIT PERCENT; SCALE_H; }
		BOOL SCULPTDEFORMER_STAMP_ACTIVE { }
		FILENAME SCULPTDEFORMER_STAMP_TEXTURE { FIT_H; SCALE_H; }
		REAL SCULPTDEFORMER_STAMP_ROTATION { UNIT DEGREE; MIN 0; MAX 360; CUSTOMGUI REALSLIDER; SCALE_H; FIT_H;}
		LONG SCULPTDEFORMER_SEED { }
		LONG SCULPTDEFORMER_NUMSTAMPS { MIN 1; STEP 1; MINSLIDER 1; MAXSLIDER 100; SCALE_H; }

		LONG SCULPTDEFORMER_MODIFIER
		{
			CYCLE
			{
			}
		}

		BOOL SCULPTDEFORMER_STAMP_USEFALLOFF { }
		SPLINE SCULPTDEFORMER_FALLOFF_SPLINE
		{ 
			SHOWGRID_H; SHOWGRID_V; EDIT_H; EDIT_V; 
		}
	}
}
