CONTAINER overtexhandle
{
	NAME overtexhandle;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SDK_EXAMPLE_VERTEXHANDLE_POINT_A_DIST 		{ UNIT METER; }
		REAL SDK_EXAMPLE_VERTEXHANDLE_POINT_B_DIST		{ UNIT METER; }
		REAL SDK_EXAMPLE_VERTEXHANDLE_POINT_C_DIST		{ UNIT METER; }
	}
}