CONTAINER Thairsdkrendering
{
	NAME Thairsdkrendering;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		REAL HAIR_RENDERING_SHADOW { UNIT PERCENT; MIN 0.0; MAX 1000.0; MAXSLIDER 100.0; }
		REAL HAIR_RENDERING_TRANSPARENCY { UNIT PERCENT; MIN 0.0; MAX 1000.0; MAXSLIDER 100.0; }

		LONG HAIR_RENDERING_DEPTH { MIN 1; MAX 100; }
	}
}
