CONTAINER toolsculptselectionbrush
{
  NAME toolsculptselectionbrush;
  INCLUDE toolsculptbrushbase;
  HIDE MDATA_SCULPTBRUSH_STAMP_GROUP;
  HIDE MDATA_SCULPTBRUSH_STENCIL_GROUP;
  
	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;		
	}

}
