CONTAINER VPcolorize
{
	NAME VPcolorize;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		REAL VP_COLORIZE_DELTA_R	{ UNIT PERCENT; MIN -100.0; MAX 100.0; }
		REAL VP_COLORIZE_DELTA_G	{ UNIT PERCENT; MIN -100.0; MAX 100.0; }
		REAL VP_COLORIZE_DELTA_B	{ UNIT PERCENT; MIN -100.0; MAX 100.0; }
		LONG VP_COLORIZE_MODE			{ CYCLE { VP_COLORIZE_MODE_COMPLETE; VP_COLORIZE_MODE_ALPHA; VP_COLORIZE_MODE_OBJECTBUFFER; } }
		LONG VP_COLORIZE_OBJECTID { PARENTID VP_COLORIZE_MODE; MIN 1; MAX 1000; }
		LENSGLOW VP_COLORIZE_LENSGLOW { }
	}
}
