#ifndef VPSTEREO_H__
#define VPSTEREO_H__

enum
{
	VP_STEREO_CAMERAS				=	1000,
		VP_STEREO_CAMERAS_2	= 2,
		VP_STEREO_CAMERAS_3	= 3,
	VP_STEREO_SEPARATION		= 1001,
	VP_STEREO_ENABLE			= 1002
};

#endif // VPSTEREO_H__
