CONTAINER VPVisualizeChannel
{
  NAME VPVisualizeChannel;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		REAL VP_VISUALIZE_CHANNEL_STRENGTH { CUSTOMGUI REALSLIDER; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; UNIT PERCENT; }
		LONG VP_VISUALIZE_CHANNEL_CHN
		{
			CYCLE
			{
				VP_VISUALIZE_CHANNEL_CHN_UVW;
				VP_VISUALIZE_CHANNEL_CHN_DU;
				VP_VISUALIZE_CHANNEL_CHN_DV;
				VP_VISUALIZE_CHANNEL_CHN_NORMAL;
				VP_VISUALIZE_CHANNEL_CHN_DEPTH;
				VP_VISUALIZE_CHANNEL_CHN_MAT_ID;
				VP_VISUALIZE_CHANNEL_CHN_WORLD_COORDINATES;
				VP_VISUALIZE_CHANNEL_CHN_OBJECTID;
			}
		}
		REAL VP_VISUALIZE_CHANNEL_LOCLIP { CUSTOMGUI REALSLIDER; MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; }
		REAL VP_VISUALIZE_CHANNEL_HICLIP { CUSTOMGUI REALSLIDER; MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; }
	};
}
