#ifndef XSDKGRADIENT_H__
#define XSDKGRADIENT_H__

enum
{
	SDKGRADIENTSHADER_ANGLE			= 1003,	// REAL
	SDKGRADIENTSHADER_COLOR			= 1004, // GRADIENT
	SDKGRADIENTSHADER_MODE				= 1005, // LONG
		SDKGRADIENTSHADER_MODE_U						= 0,
		SDKGRADIENTSHADER_MODE_V						= 1,
		SDKGRADIENTSHADER_MODE_DIAGONAL		= 2,
		SDKGRADIENTSHADER_MODE_RADIAL			= 3,
		SDKGRADIENTSHADER_MODE_CIRCULAR		= 4,
		SDKGRADIENTSHADER_MODE_BOX					= 5,
		SDKGRADIENTSHADER_MODE_STAR				= 6,
		SDKGRADIENTSHADER_MODE_CORNER			= 7,
	SDKGRADIENTSHADER_CYCLE			= 1006,	// BOOL

	SDKGRADIENTSHADER_TURBULENCE	= 1007,
	SDKGRADIENTSHADER_OCTAVES		= 1008,
	SDKGRADIENTSHADER_SCALE			= 1009,
	SDKGRADIENTSHADER_FREQ				= 1010,
	SDKGRADIENTSHADER_ABSOLUTE		= 1011
};

#endif // XSDKGRADIENT_H__
