#ifndef MAIN_H__
#define MAIN_H__

#include "ge_prepass.h"
#include "c4d_plugin.h"

class BaseDocument;
class AtomArray;

Bool RegisterSN();
Bool RegisterGradient();
Bool RegisterBitmap();
Bool RegisterMandelbrot();
Bool RegisterSimpleMaterial();
Bool RegisterParticleVolume();
Bool RegisterMenuTest();
Bool RegisterAsyncTest();
Bool RegisterActiveObjectDlg();
Bool RegisterPGPTest();
Bool RegisterListView();
Bool RegisterSubDialog();
Bool RegisterSpherify();
Bool RegisterRoundedTube();
Bool RegisterTriangulate();
Bool RegisterVPTest();
Bool RegisterVPInvertImage();
Bool RegisterBlinker();
Bool RegisterAtomObject();
Bool RegisterCircle();
Bool RegisterGLTestMaterial();
Bool RegisterSTL();
Bool RegisterLookAtCamera();
Bool RegisterGravitation();
Bool RegisterPrimitiveTool();
Bool RegisterMorphMixer();
Bool RegisterVPVisualizeNormals();
Bool RegisterVPVisualizeChannel();
Bool RegisterVPReconstruct();
Bool RegisterExampleDataType();
Bool RegisterMemoryStat();
Bool RegisterEdgeCutTool();
Bool RegisterPickObjectTool();
Bool RegisterReverseNormals();
Bool RegisterLayerShaderBrowser();
Bool RegisterPainterSaveTest();
Bool RegisterRandomFalloff();
Bool RegisterNoiseEffector();
Bool RegisterDropEffector();
Bool RegisterDeformerObject();
Bool RegisterForceObject();
Bool RegisterCollisionObject();
Bool RegisterConstraintObject();
Bool RegisterGrassObject();
Bool RegisterShader();
Bool RegisterVideopost();
Bool RegisterStylingTag();
Bool RegisterRenderingTag();
Bool RegisterGeneratorObject();
Bool RegisterExampleSNHook();
void MiscTest();
void MiscDelegateTest();
void MaxonArrayTest();
void MoveCopyConstructorSample();
Bool RegisterPythonRegexCommand();
Bool RegisterSculptingTool();
Bool RegisterSculpt();
Bool RegisterSculptPullBrush();
Bool RegisterSculptCubesBrush();
Bool RegisterSculptDrawPolyTool();
Bool RegisterSculptSelectionBrush();
Bool RegisterSculptGrabBrush();
Bool RegisterSculptDrawPolyBrush();
Bool AddUndo(BaseDocument* doc, AtomArray* arr, UNDOTYPE type);
Bool RegisterSnapTool();
Bool RegisterSculptDeformer();
Bool RegisterSculptModifiers();
Bool RegisterSculptBrushTwist();
Bool RegisterSculptBrushMultiStamp();
Bool RegisterSnapDataNullSnap();
Bool RegisterCustomGUIString();
Bool RegisterCustomDatatypeCustomGUI();
Bool RegisterExampleDialogCommand();
Bool RegisterObjectDynamicDescription();
Bool RegisterSculptBrushSpline();
Bool RegisterGetSetDParameterExample();
Bool RegisterTakeTestCommmands();
Bool RegisterPolygonReductionTest();
Bool RegisterObjectHyperFileExample();
Bool RegisterPlaneByPolygons();
Bool RegisterGreekTemple();
Bool RegisterHeartShape();
Bool RegisterLatticePlane();
Bool RegisterLoftedMesh();
Bool RegisterPorcupine();
Bool RegisterRevolvedMesh();
Bool RegisterRuledMesh();
Bool RegisterParticlesShuffling();
Bool RegisterVertexHandle();
Bool RegisterCustomDataTagDescription();
Bool RegisterCustomDataTagCommand();

Bool RegisterPaintTool();
Bool RegisterPaintObject();

Bool RegisterPolyExample();
void CommandLineRendering(C4DPL_CommandLineArgs* args);

#endif // MAIN_H__
