#ifndef OBOUNDINGBOX_H__
#define OBOUNDINGBOX_H__

// The parameter ID enumeration for Oboudingbox.res, the Oboudingbox object.
enum
{
  ID_OBOUNDBOX_DISPLAY_MODE	= 1000,
    ID_OBOUNDBOX_DISPLAY_MODE_GOURAUD = 0,
    ID_OBOUNDBOX_DISPLAY_MODE_GOURAUD_WIRE = 1,
    ID_OBOUNDBOX_DISPLAY_MODE_QUICK = 2,
    ID_OBOUNDBOX_DISPLAY_MODE_QUICK_WIRE = 3,
    ID_OBOUNDBOX_DISPLAY_MODE_FLAT = 4,
    ID_OBOUNDBOX_DISPLAY_MODE_FLAT_WIRE = 5,
    ID_OBOUNDBOX_DISPLAY_MODE_HIDDENLINE = 6,
    ID_OBOUNDBOX_DISPLAY_MODE_NOSHADING = 7,
  ID_OBOUNDBOX_DISPLAY_MODE_GET_COUNT = 1001,
};

#endif // OBOUNDINGBOX_H__
